# Generated by Django 2.1.7 on 2019-02-20 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippets',
            old_name='snippet',
            new_name='snippets',
        ),
    ]
