# Generated by Django 2.1.7 on 2019-02-20 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190220_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippets',
            name='codelines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='main.Codelines'),
        ),
    ]
